program hyCalendarTest;

uses
  Forms,
  TestFrameWork,
  GUITestRunner,
  ImportTest in 'ImportTest.pas',
  ImportText in '..\ImportText.pas',
  CalendarItem in '..\CalendarItem.pas',
  CalendarDocument in '..\CalendarDocument.pas',
  RangeItemList in '..\RangeItemList.pas',
  RangeItem in '..\RangeItem.pas',
  DocumentReference in '..\DocumentReference.pas',
  DocumentManager in '..\DocumentManager.pas',
  RangeItemReferenceList in '..\RangeItemReferenceList.pas',
  SeriesItem in '..\SeriesItem.pas',
  SeriesItemCondition in '..\SeriesItemCondition.pas',
  TodoList in '..\TodoList.pas',
  CalendarConfig in '..\CalendarConfig.pas',
  CalendarPreview in '..\CalendarPreview.pas',
  CalendarPrintDialog in '..\CalendarPrintDialog.pas' {frmCalendarPrint},
  CalendarPrinter in '..\CalendarPrinter.pas',
  CellRenderer in '..\CellRenderer.pas',
  ConfigDialog in '..\ConfigDialog.pas' {frmConfigDialog},
  DateTimePickerEnhance in '..\DateTimePickerEnhance.pas',
  DayConditionNode in '..\DayConditionNode.pas',
  DayConditionPropertyEditDialog in '..\DayConditionPropertyEditDialog.pas' {frmDayConditionPropertyEditDialog},
  ExportDialog in '..\ExportDialog.pas' {frmExportDialog},
  FileExtRegisteration in '..\FileExtRegisteration.pas',
  FileHistory in '..\FileHistory.pas',
  FindDialog in '..\FindDialog.pas' {frmFindDialog},
  HintWindow in '..\HintWindow.pas' {frmHintWindow},
  LogicalExprNode in '..\LogicalExprNode.pas',
  LogicalExprPropertyEditDialog in '..\LogicalExprPropertyEditDialog.pas' {frmLogicalExprPropertyEditDialog},
  PageNode in '..\PageNode.pas',
  PaintColorConfigDialog in '..\PaintColorConfigDialog.pas' {frmPaintColorConfig},
  RangeItemEditDialog in '..\RangeItemEditDialog.pas' {frmRangeItemEditDialog},
  RangeItemManager in '..\RangeItemManager.pas',
  ReferenceDialog in '..\ReferenceDialog.pas' {frmReferenceDialog},
  Rokuyo in '..\Rokuyo.pas',
  SearchResult in '..\SearchResult.pas',
  SeriesItemEditDialog in '..\SeriesItemEditDialog.pas' {frmSeriesItemEditDialog},
  SeriesItemProeprtyEditDialog in '..\SeriesItemProeprtyEditDialog.pas' {frmSeriesItemPropertyEditDialog},
  SeriesItemSelectDialog in '..\SeriesItemSelectDialog.pas' {frmSeriesItemSelectDialog},
  TodoDialog in '..\TodoDialog.pas' {frmTodoDialog},
  TodolistCopy in '..\TodolistCopy.pas' {frmTodolistCopyDialog},
  TodoUpdateManager in '..\TodoUpdateManager.pas',
  PLPREVFRM in '..\lib\PLPREVFRM.pas' {plPrevForm},
  plPrev in '..\lib\plPrev.pas',
  ImportDialog in '..\ImportDialog.pas' {frmImportDialog},
  About in '..\About.pas' {frmAbout},
  AbstractDocument in '..\AbstractDocument.pas',
  Constants in '..\textutil\Constants.pas',
  DateFormat in '..\textutil\DateFormat.pas',
  StringSplitter in '..\textutil\StringSplitter.pas',
  URLScan in '..\textutil\URLScan.pas',
  ColoredStringListTest in 'ColoredStringListTest.pas',
  ColoredStringList in '..\ColoredStringList.pas',
  ColorManager in '..\ColorManager.pas',
  DateValidation in '..\textutil\DateValidation.pas',
  SeriesItemManager in '..\SeriesItemManager.pas',
  SeriesPublicHoliday in '..\SeriesPublicHoliday.pas',
  SeriesCallback in '..\SeriesCallback.pas',
  CalendarActionFactory in '..\CalendarActionFactory.pas',
  CalendarAction in '..\CalendarAction.pas',
  ColorPair in '..\textutil\ColorPair.pas',
  SeriesItemSerialize in '..\SeriesItemSerialize.pas',
  Calendar in '..\Calendar.pas' {frmCalendar},
  CalendarCallback in '..\CalendarCallback.pas',
  SeriesItemUtil in '..\SeriesItemUtil.pas',
  UndoBuffer in '..\UndoBuffer.pas',
  UndoBufferTest in 'UndoBufferTest.pas',
  DateFormatTest in 'DateFormatTest.pas',
  DateValidationTest in 'DateValidationTest.pas',
  StringSplitterTest in 'StringSplitterTest.pas',
  URLScanTest in 'URLScanTest.pas',
  SeriesItemTest in 'SeriesItemTest.pas',
  SeriesItemConditionTest in 'SeriesItemConditionTest.pas',
  SeriesPublicHolidayTest in 'SeriesPublicHolidayTest.pas',
  DayConditionNodeTest in 'DayConditionNodeTest.pas',
  DayConditionUtil in '..\DayConditionUtil.pas',
  DayConditionUtilTest in 'DayConditionUtilTest.pas',
  DocumentSaveTest in 'DocumentSaveTest.pas',
  RangeItemTest in 'RangeItemTest.pas',
  CountdownDialog in '..\CountdownDialog.pas' {frmCountdown},
  CountdownItem in '..\CountdownItem.pas',
  Hyperlinks in '..\Hyperlinks.pas';

{$R *.res}

begin
 Application.Initialize;
 GUITestRunner.RunRegisteredTests;
end.
